### ISSUE TITLE
Fails to build with mingw64 due to usage of "PIE" option on system without explicit PIE

### ISSUE THREAD

**Issue by charlemagnelasse** [mupen64plus/mupen64plus-ui-console#67]
It was noticed that 7b236510288eece4cb824d9155005f83d1e4d0d2 breaks the build under mingw64:

    x86_64-w64-mingw32.shared-gcc: error: unrecognized command line option '-no-pie'

This change was introduced with #65 after #61 was opened.

**Comment by Narann** [comment]
Thanks for reporting.

The code is following:

```makefile
ifndef PIE
  ifeq ($(CC),$(CROSS_COMPILE)gcc)
    # check if PIE is the default for the compiler
    PIE_DEFAULT = $(shell $(CC) -v 2>&1 | grep enable-default-pie)
    ifeq ($(PIE_DEFAULT),)
      PIE = 1
    endif
  endif
endif

ifeq ($(PIE), 1)
  CFLAGS += -fPIE
  LDFLAGS += -pie
else
  CFLAGS += -fno-PIE
  LDFLAGS += -no-pie
endif
```

I suspect the last else statement is reached if PIE is not defined.

Maybe change this last statement to:

```makefile
ifdef PIE
  ifeq ($(PIE), 1)
    CFLAGS += -fPIE
    LDFLAGS += -pie
  else
    ifeq ($(PIE), 0)
      CFLAGS += -fno-PIE
      LDFLAGS += -no-pie
    else
      $(error Invalid PIE value.)
    endif
  endif
endif
```

Does it work for both of you @charlemagnelasse and @orbea ?

**Comment by Jj0YzL5nvJ** [comment]
> x86_64-w64-mingw32.shared-gcc

SHARED is `PIE`... but I don't know if shared can even be `no-PIE`... and is x86 **over x64** ¬¬u
https://stackoverflow.com/questions/43367427/32-bit-absolute-addresses-no-longer-allowed-in-x86-64-linux

**Comment by charlemagnelasse** [comment]
@Narann, seems to build for me with this change.

**Comment by orbea** [comment]
@Narann Sorry for the regression, your proposed change works fine for me on both gentoo and slackware.

**Comment by charlemagnelasse** [comment]
What must be done to get it fixed? I saw @Narann commit changes to other repositories but this change was not applied yet - so maybe we are missing something here.

**Comment by Narann** [comment]
I think we only need a PR to fix this.

**Comment by orbea** [comment]
@ Narann I based it upon your example above if that's okay? https://github.com/mupen64plus/mupen64plus-ui-console/issues/67

**Comment by Narann** [comment]
Fixed by #69

**Comment by charlemagnelasse** [comment]
@Narann Please reopen this ticket. Your change doesn't fix the problem because it forgot to remove following block:

```
ifeq ($(PIE), 1)
  CFLAGS += -fPIE
  LDFLAGS += -pie
else
  CFLAGS += -fno-PIE
  LDFLAGS += -no-pie
endif
```

**Comment by Narann** [comment]
:facepalm: 

Sorry, should be fixed in #70

**Comment by charlemagnelasse** [comment]
Seems like it is building now. thanks

**Comment by Narann** [comment]
Sorry for the inconvenience.
